name: Check Modified Assets

on:
    pull_request:

jobs:
    build-trunk:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: trunk
            - name: Setup node version and npm cache
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'
            - name: npm install and build
              run: |
                  npm ci --no-optional
                  npm run build:check-assets
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: assets-list
                  path: ./build/assets.json

    compare-assets-with-trunk:
        needs: [build-trunk]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Cache node_modules
              id: cache-node-modules
              uses: actions/cache@v3
              cache-name: cache-node-modules
              with:
                  path: node_modules
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - if: ${{ steps.cache-node-modules.outputs.cache-hit == false }}
              name: List the state of node modules
              continue-on-error: true
              run: npm list

            - name: Setup node version and npm cache
              uses: actions/setup-node@v3
              with:
                  node-version-file: '.nvmrc'
                  cache: 'npm'

            - if: ${{ steps.cache-node-modules.outputs.cache-hit == false }}
              name: npm install
              run: npm ci --no-optional

            - name: build assets
              run: npm run build:check-assets

            - name: Download assets (trunk)
              uses: actions/download-artifact@v3
              with:
                  name: assets-list
                  path: assets-list
            - name: Compare Assets
              uses: ./.github/compare-assets
              with:
                  repo-token: '${{ secrets.GITHUB_TOKEN }}'
                  compare: assets-list/assets.json
